### ISSUE TITLE
Issue-Update websocket_klines.js

### ISSUE THREAD

**Issue by L-Nova0211** [L-Nova0211/future-scannar-crypto#127]
Automated Review Comments
Issues in backend/websocket_klines.js:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')

**Comment by code539** [comment]
I got it.
