### ISSUE TITLE
Issue-fix: I hope this is real final updating, but threshold value is 0.5 for test.

### ISSUE THREAD

**Issue by L-Nova0211** [L-Nova0211/future-scannar-crypto#131]
Automated Review Comments
Issues in backend/server.js:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')

**Comment by code539** [comment]
I got it.
