### ISSUE TITLE
Issue-fix:history

### ISSUE THREAD

**Issue by L-Nova0211** [L-Nova0211/future-scannar-crypto#147]
Automated Review Comments
Issues in backend/index.js:
  - (1, 'Hardcoded string found')
Issues in backend/package-lock.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (135, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Line exceeds 80 characters')
  - (139, 'Hardcoded string found')
  - (141, 'Line exceeds 80 characters')
  - (141, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Line exceeds 80 characters')
  - (146, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Line exceeds 80 characters')
  - (155, 'Hardcoded string found')
  - (156, 'Line exceeds 80 characters')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Line exceeds 80 characters')
  - (170, 'Hardcoded string found')
  - (171, 'Line exceeds 80 characters')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Line exceeds 80 characters')
  - (181, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (185, 'Line exceeds 80 characters')
  - (185, 'Hardcoded string found')
  - (186, 'Line exceeds 80 characters')
  - (186, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Line exceeds 80 characters')
  - (197, 'Hardcoded string found')
  - (198, 'Line exceeds 80 characters')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (223, 'Line exceeds 80 characters')
  - (223, 'Hardcoded string found')
  - (224, 'Line exceeds 80 characters')
  - (224, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (236, 'Line exceeds 80 characters')
  - (236, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (240, 'Line exceeds 80 characters')
  - (240, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Line exceeds 80 characters')
  - (247, 'Hardcoded string found')
  - (248, 'Line exceeds 80 characters')
  - (248, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (252, 'Line exceeds 80 characters')
  - (252, 'Hardcoded string found')
  - (253, 'Line exceeds 80 characters')
  - (253, 'Hardcoded string found')
  - (256, 'Hardcoded string found')
  - (257, 'Line exceeds 80 characters')
  - (257, 'Hardcoded string found')
  - (258, 'Line exceeds 80 characters')
  - (258, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
Issues in backend/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in backend/server.js:
  - (30, 'Hardcoded string found')
Issues in backend/ws.js:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (114, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (126, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
Issues in frontend/src/App.jsx:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
Issues in frontend/src/pages/History.jsx:
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
Issues in frontend/src/pages/Long.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
Issues in frontend/src/pages/Short.jsx:
  - (32, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
Issues in frontend/src/partials/dashboard/LongSignal.jsx:
  - (8, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
Issues in frontend/src/partials/dashboard/ShortSignal.jsx:
  - (8, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')

**Comment by scdnj** [comment]
I got it.
