### ISSUE TITLE
Issue-Merge branch 'master' of https://github.com/xfactor-toml/future-crypto-scanner into backend_contiuous_change_detection

### ISSUE THREAD

**Issue by L-Nova0211** [L-Nova0211/future-scannar-crypto#151]
Automated Review Comments
Issues in backend/index.js:
  - (1, 'Hardcoded string found')
Issues in backend/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in backend/server.js:
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
Issues in backend/websocket_klines.js:
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')

**Comment by code539** [comment]
I got it.
