### ISSUE TITLE
Issue-reconnecting WebSocket

### ISSUE THREAD

**Issue by L-Nova0211** [L-Nova0211/future-scannar-crypto#91]
Automated Review Comments
Issues in backend/ws.js:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
Issues in frontend/index.html:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in frontend/src/pages/Dashboard.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
Issues in frontend/src/pages/Hot.jsx:
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (107, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (112, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (120, 'Line exceeds 80 characters')
  - (122, 'Line exceeds 80 characters')
  - (122, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (126, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (130, 'Line exceeds 80 characters')
Issues in frontend/src/pages/Long.jsx:
  - (11, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
Issues in frontend/src/pages/Short.jsx:
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
Issues in frontend/src/partials/MarqueeNav.jsx:
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
Issues in frontend/src/partials/Sidebar.jsx:
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (145, 'Hardcoded string found')
Issues in frontend/src/partials/dashboard/HotSignal.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
Issues in frontend/src/partials/dashboard/LongSignal.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
Issues in frontend/src/partials/dashboard/ShortSignal.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')

**Comment by scdnj** [comment]
I got it.
